import { Figtree } from "next/font/google";
import "./globals.css";
import { Header } from "./components/Header";

const figtree = Figtree({ subsets: ["latin"] });

export const Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export const PageLayout = ({ children }) => {
  return <main className="page-padding">{children}</main>;
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${figtree.className} overflow-x-hidden bg-KVS-primary bg-opacity-75`}
      >
        <Header />
        <PageLayout>{children}</PageLayout>
      </body>
    </html>
  );
}
