"use client"

import { Figtree } from "next/font/google";
import "./globals.css";
import { Footer } from "./components/navigation/Footer";
import Header from "./components/navigation/Header";


const figtree = Figtree({ subsets: ["latin"] });

export const Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export const PageLayout = ({ children }) => {
  return <main className="page-padding grid gap-32">{children}</main>;
};

export default function RootLayout({ children }) {

  return (
    <html lang="en">
      <body
        className={`${figtree.className} overflow-x-hidden bg-gradient-to-b from-[#5b95ca] to-[#596d80]`}
      >
        <Header 
        />
        <PageLayout>{children}</PageLayout>
        <Footer />
      </body>
    </html>
  );
}
